// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file ros2Int.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _ros2Int_H_
#define _ros2Int_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>

/*!
 * @brief This struct represents the structure ros2Int defined by the user in the IDL file.
 * @ingroup ROS2INT
 */
typedef struct ros2Int
{
    int32_t data;
} ros2Int;

struct ucdrBuffer;

bool ros2Int_serialize_topic(struct ucdrBuffer* writer, const ros2Int* topic);
bool ros2Int_deserialize_topic(struct ucdrBuffer* reader, ros2Int* topic);
bool _Int32_cdr_serialize(const void * ros_msg,struct ucdrBuffer * cdr);
uint32_t ros2Int_size_of_topic(const ros2Int* topic, uint32_t size);


#ifdef __cplusplus
}
#endif

#endif // _ros2Int_H_