// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file ros2Int.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "ros2Int.h"
#include <stdio.h>
#include <ucdr/microcdr.h>
#include <string.h>

bool ros2Int_serialize_topic(ucdrBuffer* writer, const ros2Int* topic)
{
    (void) ucdr_serialize_int32_t(writer, topic->data);

    return !writer->error;
}

bool ros2Int_deserialize_topic(ucdrBuffer* reader, ros2Int* topic)
{
    (void) ucdr_deserialize_int32_t(reader, &topic->data);

    return !reader->error;
}

bool _Int32_cdr_serialize(const void * ros_msg,ucdrBuffer * cdr){
    (void) ros_msg;
    (void) cdr;
    bool rv = false;
    if(!ros_msg){
        printf("message handle is null");
        return false;
    }
    ros2Int * rmsg=(ros2Int*)ros_msg;
    (void)rmsg;
    rv = ucdr_serialize_int32_t(cdr,rmsg->data);
    return rv;
}

uint32_t ros2Int_size_of_topic(const ros2Int* topic, uint32_t size)
{
    uint32_t previousSize = size;
    size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
